const products = [
  {
    id: 1,
    name: "Smart Watch",
    description: "A stylish smart watch with all the latest features.",
    image: "https://via.placeholder.com/150",
    tags: ["tech", "fashion"],
  },
  {
    id: 2,
    name: "Wireless Headphones",
    description: "High-quality sound without the wires.",
    image: "https://via.placeholder.com/150",
    tags: ["tech", "music"],
  },
  {
    id: 3,
    name: "Personalized Mug",
    description: "A custom mug with a photo or message.",
    image: "https://via.placeholder.com/150",
    tags: ["sentimental", "creative"],
  },
  {
    id: 4,
    name: "Gourmet Coffee Set",
    description: "A selection of the finest coffees from around the world.",
    image: "https://via.placeholder.com/150",
    tags: ["foodie"],
  },
  {
    id: 5,
    name: "Leather Journal",
    description: "A beautiful leather-bound journal for thoughts and ideas.",
    image: "https://via.placeholder.com/150",
    tags: ["creative", "sentimental"],
  },
  {
    id: 6,
    name: "Designer Sunglasses",
    description: "Protect your eyes in style with these designer shades.",
    image: "https://via.placeholder.com/150",
    tags: ["fashion"],
  },
  {
    id: 7,
    name: "Yoga Mat",
    description: "A high-quality, non-slip yoga mat for the fitness enthusiast.",
    image: "https://via.placeholder.com/150",
    tags: ["fitness", "wellness"],
  },
  {
    id: 8,
    name: "Artisan Chocolate Box",
    description: "A box of handcrafted chocolates for the sweet tooth.",
    image: "https://via.placeholder.com/150",
    tags: ["foodie"],
  },
  {
    id: 9,
    name: "Portable Bluetooth Speaker",
    description: "Take your music anywhere with this portable speaker.",
    image: "https://via.placeholder.com/150",
    tags: ["tech", "music"],
  },
  {
    id: 10,
    name: "Engraved Pen",
    description: "A classic and sophisticated gift.",
    image: "https://via.placeholder.com/150",
    tags: ["sentimental", "professional"],
  },
  {
    id: 11,
    name: "Subscription Box",
    description: "A monthly subscription box tailored to their interests.",
    image: "https://via.placeholder.com/150",
    tags: ["hobby"],
  },
  {
    id: 12,
    name: "Scented Candle Set",
    description: "A set of aromatic candles to create a relaxing atmosphere.",
    image: "https://via.placeholder.com/150",
    tags: ["wellness", "home"],
  },
  {
    id: 13,
    name: "Cocktail Making Kit",
    description: "Everything you need to become a master mixologist.",
    image: "https://via.placeholder.com/150",
    tags: ["hobby", "foodie"],
  },
  {
    id: 14,
    name: "Cashmere Scarf",
    description: "A luxurious and warm cashmere scarf.",
    image: "https://via.placeholder.com/150",
    tags: ["fashion", "sentimental"],
  },
  {
    id: 15,
    name: "DIY Craft Kit",
    description: "A fun and creative DIY kit for a new hobby.",
    image: "https://via.placeholder.com/150",
    tags: ["creative", "hobby"],
  },
];

module.exports = products;